### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by jayleswo** [oznogon/EmptyEpsilon#7]
Crashes when I attempt to open on my Mac

Process:               EmptyEpsilon [88135]
Path:                  /Users/USER/Downloads/EmptyEpsilon.app/Contents/MacOS/EmptyEpsilon
Identifier:            EmptyEpsilon
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           EmptyEpsilon [88135]
User ID:               501

Date/Time:             2016-07-23 14:10:20.078 -0700
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11
Anonymous UUID:        7CB50F85-A72B-7C75-816C-74752E09D89F

Sleep/Wake UUID:       216B769B-14A2-4AD2-B4F1-62C054A5C3EF

Time Awake Since Boot: 910000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libsfml-system.2.3.dylib
  Referenced from: /Users/USER/Downloads/EmptyEpsilon.app/Contents/MacOS/EmptyEpsilon
  Reason: image not found

Binary Images:
    0x7fff60beb000 -     0x7fff60c2225f  dyld (360.22) <A468D85E-D8D6-3461-8C99-49D3B9ACFC63> /usr/lib/dyld
    0x7fff8cef3000 -     0x7fff8d247fff  com.apple.Foundation (6.9 - 1259) <71A9D3A0-0B1F-3E3A-86F3-1486365A6EF2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff996b6000 -     0x7fff996c4fff  com.apple.opengl (12.1.0 - 12.1.0) <BBC4458E-12FC-3C9B-BF7E-6985D61C7A67> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL

Model: Macmini6,2, BootROM MM61.0106.B0A, 4 processors, Intel Core i7, 2.3 GHz, 16 GB, SMC 2.8f0
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x4B485831363030433953332F384720202020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x0198, 0x4B485831363030433953332F384720202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x10E), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.5f3 17904, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS541010A9E662, 1 TB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Hub
USB Device: Hub
USB Device: Microsoft Wheel Mouse Optical¬Æ
USB Device: Apple Pro Keyboard
USB Device: USB 3.0 Bus
Thunderbolt Bus: Mac mini, Apple Inc., 23.4

**Comment by oznogon** [comment]
Are you launching from the release build at https://github.com/oznogon/EmptyEpsilon/releases/tag/EE-OSX-20160624, or building it from source?

**Comment by jayleswo** [comment]
I am launching from the release build.

**Comment by oznogon** [comment]
I can't reproduce it, but I have SFML installed. I suspect that the SFML dylibs need to either be installed or bundled with the app to avoid needing to install SFML. Bundling them is non-trivial, and I'm about to leave for a few weeks on vacation, so I won't have a quick fix.

If you have homebrew installed, can you install SFML (`brew install sfml`) and report if that fixes it? 

If you don't have homebrew installed, can you [download and install SFML manually](http://www.sfml-dev.org/download/sfml/2.3.2/)?

**Comment by jayleswo** [comment]
Ok! I installed SFML. That worked. Thanks!

**Comment by oznogon** [comment]
:+1:
